# Generated by Django 5.2.4 on 2025-08-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
